spring.application.name=spring

#Configuration of connection with PostgreSQL (from docker-compose.yaml file)
spring.datasource.url=jdbc:postgresql://localhost:5332/marekbase
spring.datasource.username=marek
spring.datasource.password=password

spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate configuration
# Automatically drops and recreates the database schema on startup/shutdown
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# SQL logging configuration (shows executed SQL queries in output console)
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
